version: '3'
services:
  config_server:
    restart: always  
    build: ../
    depends_on:
      - postgres
    env_file:
      - ./env
    ports:
      - "8080:8080"
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    env_file:
      - ./env
      